version: '3'

services:
  postgres:
    image: postgres:9.6.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
